---
- name: Configuring tomcat8
  hosts: all
  tasks:
   - name: Install tomcat8
     apt:
      name: tomcat8
      state: present
   - name: Copy tomcat-users.xml file
     copy:
      src: /home/ubuntu/tomcat-users.xml
      dest: /etc/tomcat8
   - name: Change port of tomcat8 from 9090 to 8080
     replace:
      regexp: 9090
      replace: 8080
      path: /etc/tomcat8/server.xml
   - name: Restart tomcat8
     service:
      name: tomcat8
      state: restarted
   - name: Pause for 2 seconds
     pause:
      seconds: 2
   - name: Check url response of server1
     uri:
      url: http://172.31.30.195:8080
      status: 200
   - name: Check url reponse of server2
     uri:
      url: http://172.31.21.157:8080
      status: 200
   - name: Check url reponse of server3
     uri:
      url: http://172.31.30.147:8080
      status: 200
